### ISSUE TITLE
Expose an interface to "docker-compose up" without a service name

### ISSUE THREAD

**Issue by pazams** [axiomzen/zest#44]
Currently we have to specify which service we want to delegate a call to `docker-compose up`.
The command without any service is useful since it is essentially a "run all" command.

So in a `Peelfile`, instead of
`run: foo`

We would be able to also do
`run: `

The use case for it would be a micro service environment with multiple api's without a  "parent" one that can contain them all as dependencies.

**Comment by chrisaxiom** [comment]
Note to self; `docker-compose up` by default will bring up all containers (while respecting `depends_on` flags)

**Comment by pazams** [comment]
Low ROI, we can always add a "parent" service in docker compose to wrap over all the rest. Closing.
