### ISSUE TITLE
From Scratch + SSL Certs

### ISSUE THREAD

**Issue by chrisaxiom** [axiomzen/zest#9]
If you need to do `https` from a `FROM scratch` container you will need ca_certificates installed.

**Comment by chrisaxiom** [comment]
This is another way, which won't fail to download and is cacheable: https://medium.com/on-docker/use-multi-stage-builds-to-inject-ca-certs-ad1e8f01de1b

**Comment by chrisaxiom** [comment]
Also, using an `ADD` command with a URL changes the image digest even if the file is unchanged

**Comment by AndrewBurian** [comment]
The new suggestion for this is [distroless](https://github.com/GoogleContainerTools/distroless)
